/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javabase_jni_HelloJNI */

#ifndef _Included_javabase_jni_HelloJNI
#define _Included_javabase_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javabase_jni_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabase_jni_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
